[project]
name = "formanalyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.6",
    "odmantic>=1.0.2",
    "pytest>=8.3.4",
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]
